server:
  port: 8070

spring:
  application:
    name: zuul-server

  #关闭热部署日志
  devtools:
    restart:
      log-condition-evaluation-delta: false

zuul:
  routes:
    #/base/ 开头匹配到service-producer
    base:
      path: /base/**
      serviceId: base-client
    #/api-b/ 开头匹配到service-producer
    api-b:
      path: /api-b/**
      serviceId: service-producer
    #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://github.com/
